apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
       app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: rajsingh6/userservice:v2
        ports:
          - containerPort: 8050
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            value: postgres-service

---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    type: ClusterIP
    selector:
        app: user
    ports:
    - port: 8050
      targetPort: 8050
        